"""
analyze.py — Generate all paper figures from experiment results.

Produces:
    - Table 1: Main results (return + attention usage)
    - Figure 3: Learning curves
    - Figure 4: Performance-compute Pareto frontier
    - Figure 5: Gate activation vs surprise correlation
    - Figure 6: Attention usage under corruption

Note: Figures 1-2 are hand-drawn architecture/environment diagrams
(not generated by this script).
"""

import os
import numpy as np
import pandas as pd

# Set non-interactive backend before importing pyplot.
# This ensures the script works on headless servers (no display).
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from scipy import stats

# ─────────────────────────────────────────────
# Global plot style
# ─────────────────────────────────────────────

plt.rcParams.update({
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.labelsize": 12,
    "legend.fontsize": 10,
    "figure.dpi": 150,
    "savefig.dpi": 300,
    "savefig.bbox": "tight",
})

# ─────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────

RESULTS_DIR = "results"
FIGURES_DIR = "paper_figures"
os.makedirs(FIGURES_DIR, exist_ok=True)

MODELS = ["mlp", "gru", "transformer", "fixed_mixture", "aod"]
MODEL_LABELS = {
    "mlp": "MLP",
    "gru": "GRU",
    "transformer": "Transformer (Full Attn)",
    "fixed_mixture": "Fixed Mixture (ω=0.5)",
    "aod": "AoD (Ours)",
}
ENVS = ["MemoryS7", "DoorKey", "DynamicObstacles"]
SEEDS = [0, 1, 2, 3, 4]

COLORS = {
    "mlp": "#888888",
    "gru": "#2196F3",
    "transformer": "#F44336",
    "fixed_mixture": "#FF9800",
    "aod": "#4CAF50",
}

# Minimum number of seeds required to report a confidence band
MIN_SEEDS_FOR_BAND = 2


# ─────────────────────────────────────────────
# Data loading
# ─────────────────────────────────────────────

def load_results_from_pattern(exp_name_pattern, seeds=SEEDS):
    """
    Load metrics.csv for experiments named:
        {exp_name_pattern}_seed{seed}
    """
    dfs = []
    for seed in seeds:
        path = os.path.join(
            RESULTS_DIR,
            f"{exp_name_pattern}_seed{seed}",
            "metrics.csv",
        )
        if os.path.exists(path):
            df = pd.read_csv(path)
            df["seed"] = seed
            dfs.append(df)
        else:
            print(f"  [load] Missing: {path}")

    if not dfs:
        return None
    return pd.concat(dfs, ignore_index=True)


def load_results(model, env, seeds=SEEDS):
    """Standard loader for main benchmark runs: {model}_{env}_seed{seed}"""
    return load_results_from_pattern(f"{model}_{env}", seeds=seeds)


# ─────────────────────────────────────────────
# Metric extraction
# ─────────────────────────────────────────────

def get_final_return_from_pattern(exp_name_pattern, seeds=SEEDS,
                                  last_frac=0.05, last_n_fallback=10):
    """
    Compute mean and std of final returns across seeds.

    Uses the last `last_frac` fraction of each seed's data (default 5%).
    Falls back to `last_n_fallback` rows if the fraction yields fewer rows.
    Returns (mean, std). std is NaN if fewer than 2 seeds have data.
    """
    df = load_results_from_pattern(exp_name_pattern, seeds=seeds)
    if df is None:
        return np.nan, np.nan

    finals = []
    for seed in seeds:
        seed_df = df[df["seed"] == seed]
        if len(seed_df) == 0 or "mean_return" not in seed_df.columns:
            continue

        n_tail = max(
            int(len(seed_df) * last_frac),
            min(last_n_fallback, len(seed_df)),
        )
        tail = seed_df.tail(n_tail)
        finals.append(tail["mean_return"].mean())

    if not finals:
        return np.nan, np.nan

    mean = float(np.mean(finals))
    std = float(np.std(finals)) if len(finals) >= 2 else np.nan
    return mean, std


def get_final_return(model, env, seeds=SEEDS, **kwargs):
    return get_final_return_from_pattern(f"{model}_{env}", seeds=seeds, **kwargs)


def get_mean_omega_from_pattern(exp_name_pattern, seeds=SEEDS,
                                last_frac=0.05, last_n_fallback=10):
    """Compute mean gate value (omega) over the final portion of training."""
    df = load_results_from_pattern(exp_name_pattern, seeds=seeds)
    if df is None:
        return np.nan

    finals = []
    for seed in seeds:
        seed_df = df[df["seed"] == seed]
        if len(seed_df) == 0 or "mean_omega" not in seed_df.columns:
            continue

        n_tail = max(
            int(len(seed_df) * last_frac),
            min(last_n_fallback, len(seed_df)),
        )
        tail = seed_df.tail(n_tail)
        finals.append(tail["mean_omega"].mean())

    return float(np.mean(finals)) if finals else np.nan


def get_mean_omega(model, env, seeds=SEEDS, **kwargs):
    return get_mean_omega_from_pattern(f"{model}_{env}", seeds=seeds, **kwargs)


# ─────────────────────────────────────────────
# Table 1: Main results
# ─────────────────────────────────────────────

def make_results_table():
    print("\n" + "=" * 100)
    print("TABLE 1: Main Results")
    print("=" * 100)

    header = f"{'Model':<25}"
    for env in ENVS:
        header += f"  {env:<20}"
    header += f"  {'Mean ω':<10}"
    print(header)
    print("-" * 100)

    rows = []
    for model in MODELS:
        row = {"model": MODEL_LABELS[model]}
        for env in ENVS:
            mean, std = get_final_return(model, env)
            row[env] = (mean, std)

        # Omega per environment (not just MemoryS7)
        row["mean_omega"] = {}
        for env in ENVS:
            row["mean_omega"][env] = get_mean_omega(model, env)

        rows.append(row)

        # Print table row — report MemoryS7 omega as the canonical value
        line = f"{MODEL_LABELS[model]:<25}"
        for env in ENVS:
            m, s = row[env]
            if np.isnan(m):
                line += f"  {'N/A':<20}"
            elif np.isnan(s):
                line += f"  {m:6.2f} (1 seed)     "
            else:
                line += f"  {m:6.2f} ± {s:4.2f}     "

        omega = row["mean_omega"]["MemoryS7"]
        line += f"  {omega:.3f}" if not np.isnan(omega) else "  N/A"
        print(line)

    print("=" * 100)

    # Export machine-readable summary
    export_summary(rows)
    return rows


def export_summary(rows):
    """Save results as CSV for easy reference in paper writing."""
    records = []
    for row in rows:
        for env in ENVS:
            m, s = row[env]
            records.append({
                "model": row["model"],
                "env": env,
                "mean_return": m,
                "std_return": s,
                "mean_omega": row["mean_omega"][env],
            })
    path = os.path.join(FIGURES_DIR, "summary.csv")
    pd.DataFrame(records).to_csv(path, index=False)
    print(f"Saved: {path}")


# ─────────────────────────────────────────────
# Figure 3: Learning curves
# ─────────────────────────────────────────────

def plot_learning_curves():
    fig, axes = plt.subplots(1, len(ENVS), figsize=(15, 4))
    any_plotted = False

    for ax, env in zip(axes, ENVS):
        env_plotted = False
        for model in MODELS:
            df = load_results(model, env)
            if df is None:
                print(f"  Warning: No data for {model}/{env}")
                continue
            if "global_step" not in df.columns or "mean_return" not in df.columns:
                print(
                    f"  Warning: Missing columns for {model}/{env} "
                    f"(have: {list(df.columns)})"
                )
                continue

            grouped = df.groupby("global_step")["mean_return"]
            mean = grouped.mean()
            std = grouped.std().fillna(0.0)
            count = grouped.count()

            ax.plot(
                mean.index,
                mean.values,
                label=MODEL_LABELS[model],
                color=COLORS[model],
                linewidth=2,
            )

            # Only show confidence band where we have enough seeds
            band_mask = count >= MIN_SEEDS_FOR_BAND
            band_mean = mean[band_mask]
            band_std = std[band_mask]
            if len(band_mean) > 0:
                ax.fill_between(
                    band_mean.index,
                    band_mean.values - band_std.values,
                    band_mean.values + band_std.values,
                    alpha=0.15,
                    color=COLORS[model],
                )

            env_plotted = True
            any_plotted = True

        ax.set_title(env, fontweight="bold")
        ax.set_xlabel("Environment Steps")
        ax.set_ylabel("Mean Episode Return")
        ax.grid(True, alpha=0.3)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)

        if not env_plotted:
            ax.text(
                0.5, 0.5, "No data available",
                transform=ax.transAxes, ha="center", va="center",
                fontsize=12, color="gray",
            )

    axes[0].legend(loc="upper left", fontsize=9)
    plt.tight_layout()

    if not any_plotted:
        print("Warning: No data found for any model/env — skipping fig3")
        plt.close()
        return

    path = os.path.join(FIGURES_DIR, "fig3_learning_curves.pdf")
    plt.savefig(path, bbox_inches="tight")
    print(f"Saved: {path}")
    plt.close()


# ─────────────────────────────────────────────
# Figure 4: Pareto frontier
# ─────────────────────────────────────────────

def plot_pareto_frontier():
    lambdas = [0.001, 0.005, 0.01, 0.05, 0.1]
    env = "MemoryS7"

    fig, ax = plt.subplots(figsize=(7, 5))
    any_plotted = False

    # AoD lambda sweep
    aod_points = []
    for lam in lambdas:
        lam_str = f"{lam:g}"
        exp_name = f"aod_lambda{lam_str}_{env}"
        mean_ret, std_ret = get_final_return_from_pattern(exp_name)
        mean_omega = get_mean_omega_from_pattern(exp_name)

        if not np.isnan(mean_ret) and not np.isnan(mean_omega):
            aod_points.append((mean_omega, mean_ret, std_ret, lam))

    if aod_points:
        aod_points = sorted(aod_points, key=lambda x: x[0])
        omegas = [p[0] for p in aod_points]
        returns = [p[1] for p in aod_points]
        stds = [p[2] if not np.isnan(p[2]) else 0.0 for p in aod_points]

        ax.errorbar(
            omegas,
            returns,
            yerr=stds,
            fmt="o-",
            color=COLORS["aod"],
            linewidth=2,
            markersize=8,
            capsize=3,
            label="AoD (varying λ)",
            zorder=5,
        )
        for o, r, s, lam in aod_points:
            ax.annotate(
                f"{lam:g}", (o, r),
                textcoords="offset points", xytext=(4, 4), fontsize=8,
            )
        any_plotted = True

    # Baseline anchors
    # Note: omega values for baselines are conceptual anchors, not measured:
    #   GRU = 0.0 (pure recurrence, no attention)
    #   Transformer = 1.0 (full attention every step)
    #   Fixed Mixture = 0.5 (hardcoded blend)
    baseline_omega = {"gru": 0.0, "transformer": 1.0, "fixed_mixture": 0.5}

    for model in ["gru", "transformer", "fixed_mixture"]:
        mean_ret, std_ret = get_final_return(model, env)
        if np.isnan(mean_ret):
            print(f"  Warning: No data for baseline {model}/{env} in Pareto plot")
            continue

        omega = baseline_omega[model]
        yerr = std_ret if not np.isnan(std_ret) else 0.0
        ax.scatter(
            omega,
            mean_ret,
            s=120,
            color=COLORS[model],
            label=MODEL_LABELS[model],
            zorder=6,
            marker="*",
        )
        ax.errorbar(
            omega, mean_ret, yerr=yerr,
            color=COLORS[model], capsize=3, alpha=0.5,
        )
        any_plotted = True

    ax.set_xlabel(r"Mean Attention Usage $\mathbb{E}[\omega_t]$")
    ax.set_ylabel("Mean Episode Return")
    ax.set_title("Performance–Compute Trade-off (MemoryS7)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    if not any_plotted:
        print("Warning: No data found — skipping fig4")
        plt.close()
        return

    path = os.path.join(FIGURES_DIR, "fig4_pareto.pdf")
    plt.savefig(path, bbox_inches="tight")
    print(f"Saved: {path}")
    plt.close()


# ─────────────────────────────────────────────
# Figure 5: Gate activation vs surprise
# ─────────────────────────────────────────────

def plot_gate_vs_surprise():
    """
    Plot surprise and gate activation over time for a single trajectory.

    Uses seed 0 for the qualitative visualization. The Pearson correlation
    reported in the legend is from this single trajectory; see the paper
    text for the cross-seed average.
    """
    traj_path = os.path.join(RESULTS_DIR, "aod_MemoryS7_seed0", "trajectory.npz")
    if not os.path.exists(traj_path):
        print(f"Trajectory not found at {traj_path} — skipping Figure 5")
        return

    data = np.load(traj_path)

    required_keys = {"timesteps", "surprise", "omega"}
    missing = required_keys - set(data.keys())
    if missing:
        print(f"Trajectory file missing keys {missing} — skipping Figure 5")
        return

    timesteps = data["timesteps"]
    surprise = data["surprise"]
    omega = data["omega"]

    if not (timesteps.shape == surprise.shape == omega.shape):
        print(
            f"Shape mismatch in trajectory data: timesteps={timesteps.shape}, "
            f"surprise={surprise.shape}, omega={omega.shape} — skipping Figure 5"
        )
        return

    corr, pval = stats.pearsonr(surprise, omega)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 6), sharex=True)

    ax1.plot(timesteps, surprise, color="#FF9800", linewidth=1.5,
             label=r"Surprise $s_t$")
    ax1.set_ylabel(r"Surprise $s_t$")
    ax1.fill_between(timesteps, 0, surprise, alpha=0.2, color="#FF9800")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)

    ax2.plot(
        timesteps,
        omega,
        color=COLORS["aod"],
        linewidth=1.5,
        label=rf"Gate $\omega_t$ (r={corr:.2f}, p={pval:.1e})",
    )
    ax2.fill_between(timesteps, 0, omega, alpha=0.2, color=COLORS["aod"])
    ax2.set_ylabel(r"Gate $\omega_t$")
    ax2.set_xlabel("Timestep")
    ax2.set_ylim(-0.05, 1.05)
    ax2.grid(True, alpha=0.3)
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)
    ax2.legend()

    fig.suptitle(
        "Attention Activation vs Prediction Error (MemoryS7)",
        fontweight="bold",
    )
    fig.tight_layout(rect=[0, 0, 1, 0.95])  # Leave room for suptitle

    path = os.path.join(FIGURES_DIR, "fig5_gate_vs_surprise.pdf")
    fig.savefig(path, bbox_inches="tight")
    print(f"Saved: {path} | Pearson r={corr:.3f}, p={pval:.4f}")
    plt.close(fig)


# ─────────────────────────────────────────────
# Figure 6: Corruption analysis
# ─────────────────────────────────────────────

def plot_corruption_results():
    corruption_levels = [0.0, 0.1, 0.3, 0.5]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

    aod_returns = []
    aod_omegas = []
    transformer_returns = []

    for p in corruption_levels:
        if p == 0.0:
            aod_name = "aod_MemoryS7"
            transformer_name = "transformer_MemoryS7"
        else:
            p_str = f"{p:.1f}"
            aod_name = f"aod_MemoryS7_corrupt{p_str}"
            transformer_name = f"transformer_MemoryS7_corrupt{p_str}"

        m_aod, s_aod = get_final_return_from_pattern(aod_name)
        aod_returns.append((m_aod, s_aod))
        aod_omegas.append(get_mean_omega_from_pattern(aod_name))

        m_tr, s_tr = get_final_return_from_pattern(transformer_name)
        transformer_returns.append((m_tr, s_tr))

    aod_m = np.array([x[0] for x in aod_returns], dtype=float)
    aod_s = np.array([x[1] for x in aod_returns], dtype=float)
    tr_m = np.array([x[0] for x in transformer_returns], dtype=float)
    tr_s = np.array([x[1] for x in transformer_returns], dtype=float)
    aod_omegas = np.array(aod_omegas, dtype=float)

    # Warn about missing data
    for label, arr in [
        ("AoD returns", aod_m),
        ("Transformer returns", tr_m),
        ("AoD omegas", aod_omegas),
    ]:
        nan_indices = np.where(np.isnan(arr))[0]
        if len(nan_indices) > 0:
            missing_levels = [corruption_levels[i] for i in nan_indices]
            print(f"  Warning: Missing {label} for corruption levels: {missing_levels}")

    # Filter to valid (non-NaN) points for each series
    any_plotted = False
    levels = np.array(corruption_levels)

    # Replace NaN stds with 0 for plotting (NaN std = single seed)
    aod_s_safe = np.where(np.isnan(aod_s), 0.0, aod_s)
    tr_s_safe = np.where(np.isnan(tr_s), 0.0, tr_s)

    aod_valid = ~np.isnan(aod_m)
    if np.any(aod_valid):
        ax1.plot(
            levels[aod_valid], aod_m[aod_valid],
            "o-", color=COLORS["aod"], label="AoD", linewidth=2,
        )
        ax1.fill_between(
            levels[aod_valid],
            (aod_m - aod_s_safe)[aod_valid],
            (aod_m + aod_s_safe)[aod_valid],
            alpha=0.15, color=COLORS["aod"],
        )
        any_plotted = True

    tr_valid = ~np.isnan(tr_m)
    if np.any(tr_valid):
        ax1.plot(
            levels[tr_valid], tr_m[tr_valid],
            "s--", color=COLORS["transformer"], label="Transformer", linewidth=2,
        )
        ax1.fill_between(
            levels[tr_valid],
            (tr_m - tr_s_safe)[tr_valid],
            (tr_m + tr_s_safe)[tr_valid],
            alpha=0.15, color=COLORS["transformer"],
        )
        any_plotted = True

    ax1.set_xlabel("Observation Dropout Probability")
    ax1.set_ylabel("Mean Episode Return")
    ax1.set_title("Performance Under Observation Corruption")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)

    omega_valid = ~np.isnan(aod_omegas)
    if np.any(omega_valid):
        ax2.plot(
            levels[omega_valid], aod_omegas[omega_valid],
            "o-", color=COLORS["aod"], linewidth=2,
        )
        any_plotted = True

    ax2.set_xlabel("Observation Dropout Probability")
    ax2.set_ylabel(r"Mean Gate Value $\mathbb{E}[\omega_t]$")
    ax2.set_title("Attention Usage Increases Under Uncertainty")
    ax2.set_ylim(0, 1)
    ax2.grid(True, alpha=0.3)
    ax2.spines["top"].set_visible(False)
    ax2.spines["right"].set_visible(False)

    plt.tight_layout()

    if not any_plotted:
        print("Warning: No corruption data found — skipping fig6")
        plt.close()
        return

    path = os.path.join(FIGURES_DIR, "fig6_corruption.pdf")
    plt.savefig(path, bbox_inches="tight")
    print(f"Saved: {path}")
    plt.close()


if __name__ == "__main__":
    print("Generating paper figures...")
    make_results_table()
    plot_learning_curves()
    plot_pareto_frontier()
    plot_gate_vs_surprise()
    plot_corruption_results()
    print(f"\nAll figures saved to {FIGURES_DIR}/")